### ISSUE TITLE
developer portal apple id not provided for this build

### ISSUE THREAD

**Issue by abd0ibrahim** [bitrise-steplib/steps-ios-auto-provision#111]
I faced an error while trying to auto provision

```
Error:
developer portal apple id not provided for this build
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise547694375/step_src/lib/autoprovision/auth_data.rb:21:in `validate'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise547694375/step_src/lib/autoprovision/auth_helper.rb:21:in `login'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise547694375/step_src/step.rb:25:in `<main> 
```

No field is provided to enter the portal apple id in the workflow
Any Help with it ?

**Comment by ffqs** [comment]
I have same problem, please, help
```
+------------------------------------------------------------------------------+

| (5) ios-auto-provision@1.5.2                                                 |
+------------------------------------------------------------------------------+
| id: ios-auto-provision                                                       |
| version: 1.5.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2020-02-01T18:12:45Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Successfully installed bundler-1.17.3
Parsing documentation for bundler-1.17.3
Installing ri documentation for bundler-1.17.3
Done installing documentation for bundler after 4 seconds
1 gem installed
$ bundle install
$ bundle exec ruby /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise530080915/step_src/step.rb
Params:
team_id: DQ4MSB6CFW
certificate_urls: ***
min_profile_days_valid: 0
passphrases: ***
distribution_type: ad-hoc
project_path: ./ios/[REDACTED].xcworkspace
scheme: [REDACTED]Dev
configuration: ReleaseDev
build_url: https://app.bitrise.io/build/8015ca636e66d880
build_api_token: ***
keychain_path: /Users/vagrant/Library/Keychains/login.keychain
keychain_password: ***
verbose_log: no
generate_profiles: no
Developer Portal authentication
Error:
developer portal apple id not provided for this build
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise530080915/step_src/lib/autoprovision/auth_data.rb:21:in `validate'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise530080915/step_src/lib/autoprovision/auth_helper.rb:21:in `login'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise530080915/step_src/step.rb:25:in `<main>'
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | ios-auto-provision@1.5.2 (exit code: 1)                       | 46.32 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...github.com/bitrise-steplib/steps-ios-auto-provision/issues |
| Source: https://github.com/bitrise-steplib/steps-ios-auto-provision          |
+---+---------------------------------------------------------------+----------+
```

**Comment by non-binary** [comment]
Hi @abd0ibrahim @ffqs,

Thank you for reaching out.

Can you please provide us with your bitrise.yml file as well?

Thanks,
Luna

**Comment by ffqs** [comment]
Hi @non-binary 
I changed team id and project name text to $TEAM_ID and $PROJECT_NAME for this comment
```
---
format_version: '4'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: react-native
workflows:
  android_DEV:
    steps:
    - activate-ssh-key@4.0.3:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.14: {}
    - yarn@0.0.8:
        title: Install dependencies
    - yarn@0.0.8:
        title: Lint
        inputs:
        - command: lint
    - file-downloader@1.0.1:
        inputs:
        - destination: "$PROJECT_LOCATION/app/$PROJECT_NAME.keystore"
        - source: "$BITRISEIO_ANDROID_KEYSTORE_URL"
    - change-android-versioncode-and-versionname@1.1.1:
        inputs:
        - new_version_name: 1.0.$BITRISE_BUILD_NUMBER
        - build_gradle_path: "$PROJECT_LOCATION/app/build.gradle"
    - install-missing-android-tools@2.3.5:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    - android-build@0.9.5:
        inputs:
        - variant: devRelease
        - module: "$MODULE"
        - project_location: "$PROJECT_LOCATION"
    - deploy-to-bitrise-io@1.3.19:
        inputs:
        - notify_email_list: "$QA_EMAILS"
  android_QA:
    steps:
    - activate-ssh-key@4.0.3:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.14: {}
    - yarn@0.0.8:
        title: Install dependencies
    - yarn@0.0.8:
        title: Lint
        inputs:
        - command: lint
    - file-downloader@1.0.1:
        inputs:
        - destination: "$PROJECT_LOCATION/app/$PROJECT_NAME.keystore"
        - source: "$BITRISEIO_ANDROID_KEYSTORE_URL"
    - change-android-versioncode-and-versionname@1.1.1:
        inputs:
        - new_version_name: 1.0.$BITRISE_BUILD_NUMBER
        - build_gradle_path: "$PROJECT_LOCATION/app/build.gradle"
    - install-missing-android-tools@2.3.5:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    - android-build@0.9.5:
        inputs:
        - variant: originalRelease
        - module: "$MODULE"
        - project_location: "$PROJECT_LOCATION"
    - deploy-to-bitrise-io@1.3.19:
        inputs:
        - notify_email_list: "$QA_EMAILS"
  ios_DEV:
    steps:
    - activate-ssh-key@4.0.5:
        inputs:
        - verbose: 'true'
    - git-clone@4.0.18: {}
    - yarn@0.1.1: {}
    - set-xcode-build-number@1.0.9:
        inputs:
        - build_short_version_string: 1.0.$BITRISE_BUILD_NUMBER
        - plist_path: "./ios/$PROJECT_NAME/Info.plist"
    - cocoapods-install@1.10.1:
        inputs:
        - source_root_path: "./ios"
    - ios-auto-provision@1.4.3:
        inputs:
        - team_id: $TEAM_ID
        - scheme: $PROJECT_NAMEDev
        - configuration: ReleaseDev
        - distribution_type: ad-hoc
        - project_path: "./ios/$PROJECT_NAME.xcworkspace"
    - xcode-archive@2.7.1:
        inputs:
        - configuration: ReleaseDev
        - export_method: ad-hoc
        - scheme: $PROJECT_NAMEDev
        - team_id: TEAM_ID
        - icloud_container_environment: Development
        - project_path: "./ios/$PROJECT_NAME.xcworkspace"
    - deploy-to-bitrise-io@1.9.5:
        inputs:
        - notify_email_list: "$QA_EMAILS"
    meta:
      bitrise.io:
        stack: osx-xcode-11.3.x
app:
  envs:
  - opts:
      is_expand: false
    PROJECT_LOCATION: android
  - opts:
      is_expand: false
    MODULE: app
  - opts:
      is_expand: false
    VARIANT: ''
  - opts:
      is_expand: false
    BITRISE_PROJECT_PATH: ios/$PROJECT_NAME.xcworkspace
  - opts:
      is_expand: false
    BITRISE_SCHEME: $PROJECT_NAMEDev
  - opts:
      is_expand: false
    BITRISE_EXPORT_METHOD: ad-hoc

```
