### ISSUE TITLE
Distribution type from env vars

### ISSUE THREAD

**Issue by mcaldas** [bitrise-steplib/steps-ios-auto-provision#16]
Hi,

Would be possible to set the dist type from env vars?

This would help on more complex workflows with different schemes.

**Comment by viktorbenei** [comment]
Sure, you can do that in `bitrise.yml` mode, it's perfectly fine to set an env var as the value of the input instead of an actual value ;)

If you'd have any questions or would need further assistance just let us know!
Happy Building! :)

**Comment by Diego-Franco** [comment]
any example in how to do this?

**Comment by fehersanyi-bitrise** [comment]
Hy so, you can add env vars for the steps to use, and you can set either workflow specific env vars on the web ui, or you can specify the env var when you trigger a build manually in the window where you start it.

**Comment by viktorbenei** [comment]
@Diego-Franco an example:

```
---
format_version: '6'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other
trigger_map:
- push_branch: "*"
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary

workflows:
  primary:
    steps:
    - script@1.1.5:
        title: Do anything with Script step
        inputs:
        - runner_bin: "$SCRIPT_RUNNER_PATH"
app:
  envs:
  - opts:
      is_expand: false
    SCRIPT_RUNNER_PATH: "/bin/bash"
```

Here the `script` step's `runner_bin` input is set to use the value of the `$SCRIPT_RUNNER_PATH` env var (which was set as an `app: envs:` (app env var, available for all workflows).
